### ISSUE TITLE
fairly often terminates with "*** stack smashing detected ***: mairix terminated"

### ISSUE THREAD

**Issue by GregorZattler** [rc0/mairix#14]
First time indexing my mails with via "mairix -v"  ends in:
[...]
Scanning </home/grfz/Mail/XXX/cur/1320855018.23625_16445.shi:2,S>
Scanning </home/grfz/Mail/XXX/cur/1320855021.23625_16473.shi:2,S>
**\* stack smashing detected ***: mairix terminated
Segmentation fault

When I move this last mesage (1320855021.23625_16473.shi:2,S) out of the indexed directories, delete the db lock and retriy mairix bails out somewhat later on another email.  I did this with 4 emails but mairix still worked on only a tiny proportion of my emails.

Is there anything I can do to help fix this bug (sadly no c programming skills).

I deleted my mairix.db because there were problems finding some relatively new emails.  I therefore have to reindex my mails.  Hasen't been a problem till today.  Mairix was a great help in handling my emails and I really need it.

**Comment by kinnison** [comment]
you may find pr #17 solves this for you.
