### ISSUE TITLE
accented characters support

### ISSUE THREAD

**Issue by semente** [rc0/mairix#15]
It is known that mairix do not support accented characters in its searches. This feature is foundational for many non-English speakers.

**Comment by beemill** [comment]
i have currently indexed over 300,000 e-mails in over 800 separate mbox files, so i'm using the mbox option on mairix, and so far i'm so impressed and so excited how fast it searches through all these e-mails! now i don't feel the need to convert my mboxes to maildir now. thank you for this app! I would love to see this application survive and thrive, would love to be able to search for accented characters and also unicode characters as well, specifically the Asian texts CJK. anyway, thank you again.

**Comment by bronger** [comment]
Does this mean a search for “Müller” never works? Not even if the encodings match “by accident”?

**Comment by semente** [comment]
Closing this in favor of #29
