### ISSUE TITLE
base path not interpreted relative to mairixrc

### ISSUE THREAD

**Issue by tstgruby** [rc0/mairix#3]
Hi.

I'm using mairix 0.22 under Cygwin.

The manpage says:

> base=base-directory
> 
> ...
> 
> If the path is relative, it is treated as relative to the location of the mairixrc file.

My config is:

> base=./Maildir

Obviously, the path is relative. But when I run:

```
$ mairix -f /some/dir/other/than/HOME/.mairixrc
```

mairix tries to access mails in ~/Maildir and does not find any...

**Comment by vandry** [comment]
Yeah, the documentation's claims that if the path is relative, it is treated as relative to the location of the mairixrc file appear to never have been true.

It's a strange feature. I'd rather just update the documentation to remove the claim than to implement the feature.
